# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 84532
  start_block: 0
  contracts:
  - name: MockPriceOracle
    address:
    - 0xb5C7DD9E79F73C15E9d7d385Dd94E900e0088251
    handler: src/EventHandlers.ts
    events:
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: PriceUpdated(address indexed token, uint256 priceUsd, uint256 timestamp)
    - event: TokenAdded(address indexed token, uint256 priceUsd)
    - event: TokenRemoved(address indexed token)
  - name: MockUSDC
    address:
    - 0x18d6b03A4A0499077A2dc8c45fFf8DA10aF16f64
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: Transfer(address indexed from, address indexed to, uint256 value)
  - name: MockYieldAdapter
    address:
    - 0x07bB3370AF8cd0c28dd2C8CA7186D8B790d34458
    handler: src/EventHandlers.ts
    events:
    - event: Deposited(address indexed account, address indexed receiver, uint256 amount, bytes data)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: Withdrawn(address indexed account, address indexed receiver, uint256 amount, bytes data)
    - event: YieldClaimed(address indexed account, address indexed receiver, uint256 amount, bytes data)
  - name: MockYieldProtocol
    address:
    - 0x971a23EFc273B07812807B807DA5BE3f6901155d
    handler: src/EventHandlers.ts
    events:
    - event: AdapterUpdated(address indexed adapter)
    - event: Deposited(address indexed account, address indexed receiver, uint256 amount)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: RewardRateUpdated(uint256 rewardRate)
    - event: Withdrawn(address indexed account, address indexed receiver, uint256 amount)
    - event: YieldAccrued(address indexed account, uint256 amount)
    - event: YieldClaimed(address indexed account, address indexed receiver, uint256 amount)
  - name: OpenCrateFactory
    address:
    - 0x8a966e800ECD5025190f767232CB748F0917407B
    handler: src/EventHandlers.ts
    events:
    - event: CratePurchased(uint256 indexed templateId, uint256 indexed tokenId, address indexed purchaser, address paymentToken, uint256 paymentAmount, uint64 lockupDuration, uint16 multiplierBps, uint256 timestamp)
    - event: CrateTemplateCreated(uint256 indexed templateId, string name, uint256 basePriceUsd, uint256 version)
    - event: CrateTemplateDisabled(uint256 indexed templateId)
    - event: CrateTemplateUpdated(uint256 indexed templateId, uint256 newVersion)
    - event: EmergencyWithdraw(address indexed token, uint256 amount, address indexed recipient)
    - event: LockupOptionAdded(uint256 indexed templateId, uint64 duration, uint16 multiplierBps)
    - event: LockupOptionRemoved(uint256 indexed templateId, uint64 duration, uint16 multiplierBps)
    - event: LockupOptionUpdated(uint256 indexed templateId, uint64 duration, uint16 multiplierBps)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: Paused(address account)
    - event: TreasuryUpdated(address indexed oldTreasury, address indexed newTreasury)
    - event: Unpaused(address account)
  - name: OpenCrateNFT
    address:
    - 0xaD9604B29a892A1F06BeF534c4f5Cea5Fa729CA7
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
    - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
    - event: BaseURIUpdated(string baseURI)
    - event: BoostStatusUpdated(uint256 indexed tokenId, bool active, uint16 boostMultiplierBps)
    - event: BoostUpdated(uint256 indexed tokenId, uint16 boostMultiplierBps)
    - event: CrateMinted(uint256 indexed tokenId, address indexed to, uint8 riskLevel, uint256 strategyId, address account, uint256 priceUsd, uint16 boostMultiplierBps, uint64 lockedUntil, address indexed paymentToken, uint256 paymentAmount)
    - event: EmergencyModeToggled(bool active)
    - event: EmergencyUnlock(uint256 indexed tokenId, address indexed owner)
    - event: FactoryUpdated(address indexed newFactory)
    - event: FeeDisclosureUpdated(uint256 indexed tokenId, string feeDisclosure)
    - event: LifecycleUpdated(uint256 indexed tokenId, uint64 lastRebalanceAt, uint64 nextHarvestAt, uint256 accruedYieldUsd)
    - event: LockExtended(uint256 indexed tokenId, uint64 lockedUntil)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: Paused(address account)
    - event: PositionMetricsUpdated(uint256 indexed tokenId, uint256 indexed positionIndex, (string,string,string,string,string,uint16,uint256,int256,int256,int256,int256,uint8,uint64,uint64,uint64,uint256) details)
    - event: PositionsUpdated(uint256 indexed tokenId, uint256 positionCount, address indexed updater)
    - event: PriceUpdated(uint256 indexed tokenId, uint256 priceUsd)
    - event: RevenueShareUpdated(uint256 indexed tokenId, uint16 revenueShareBps, uint16 platformFeeBps, uint16 performanceFeeBps)
    - event: RiskDisclosureUpdated(uint256 indexed tokenId, string riskDisclosure)
    - event: TokenAdded(address indexed token, uint256 priceUsd, uint8 decimals)
    - event: TokenPriceUpdated(address indexed token, uint256 priceUsd)
    - event: TokenRemoved(address indexed token)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
    - event: Unpaused(address account)
  - name: OpenCrateStrategyRegistry
    address:
    - 0x47503954B7626724FDD0DD996ac1d69B8a7d124c
    handler: src/EventHandlers.ts
    events:
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: StrategyRegistered(uint256 indexed strategyId, address indexed adapter, uint8 riskLevel)
    - event: StrategyStatusUpdated(uint256 indexed strategyId, bool active)
    - event: StrategyUpdated(uint256 indexed strategyId, address indexed adapter, uint8 riskLevel, bytes adapterData)
unordered_multichain_mode: true
preload_handlers: true
